# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FirstHW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'

  target 'FirstHWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstHWUITests' do
    # Pods for testing
  end

end
